//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12/7/2024 1:01:31 PM
namespace LendngView.Odata.LendingTrackerApi.Models
{
    /// <summary>
    /// There are no comments for BorrowerSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowerSingle")]
    public partial class BorrowerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Borrower>
    {
        /// <summary>
        /// Initialize a new BorrowerSingle object.
        /// </summary>
        public BorrowerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BorrowerSingle object.
        /// </summary>
        public BorrowerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BorrowerSingle object.
        /// </summary>
        public BorrowerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Borrower> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Transactions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> Transactions
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Transactions == null))
                {
                    this._Transactions = Context.CreateQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction>(GetPath("Transactions"));
                }
                return this._Transactions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _Transactions;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.UserSingle User
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._User == null))
                {
                    this._User = new global::LendngView.Odata.LendingTrackerApi.Models.UserSingle(this.Context, GetPath("User"));
                }
                return this._User;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.UserSingle _User;
    }
    /// <summary>
    /// There are no comments for Borrower in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BorrowerId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("BorrowerId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Borrower")]
    public partial class Borrower : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Borrower object.
        /// </summary>
        /// <param name="borrowerId">Initial value of BorrowerId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="borrowerEmail">Initial value of BorrowerEmail.</param>
        /// <param name="borrowerSms">Initial value of BorrowerSms.</param>
        /// <param name="user">Initial value of User.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Borrower CreateBorrower(global::System.Guid borrowerId, global::System.Guid userId, string borrowerEmail, string borrowerSms, global::LendngView.Odata.LendingTrackerApi.Models.User user)
        {
            Borrower borrower = new Borrower();
            borrower.BorrowerId = borrowerId;
            borrower.UserId = userId;
            borrower.BorrowerEmail = borrowerEmail;
            borrower.BorrowerSms = borrowerSms;
            if ((user == null))
            {
                throw new global::System.ArgumentNullException("user");
            }
            borrower.User = user;
            return borrower;
        }
        /// <summary>
        /// There are no comments for Property BorrowerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowerId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BorrowerId is required.")]
        public virtual global::System.Guid BorrowerId
        {
            get
            {
                return this._BorrowerId;
            }
            set
            {
                this.OnBorrowerIdChanging(value);
                this._BorrowerId = value;
                this.OnBorrowerIdChanged();
                this.OnPropertyChanged("BorrowerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _BorrowerId;
        partial void OnBorrowerIdChanging(global::System.Guid value);
        partial void OnBorrowerIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "UserId is required.")]
        public virtual global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property IsEligible in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsEligible")]
        public virtual global::System.Nullable<bool> IsEligible
        {
            get
            {
                return this._IsEligible;
            }
            set
            {
                this.OnIsEligibleChanging(value);
                this._IsEligible = value;
                this.OnIsEligibleChanged();
                this.OnPropertyChanged("IsEligible");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsEligible;
        partial void OnIsEligibleChanging(global::System.Nullable<bool> value);
        partial void OnIsEligibleChanged();
        /// <summary>
        /// There are no comments for Property BorrowerEmail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowerEmail")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BorrowerEmail is required.")]
        public virtual string BorrowerEmail
        {
            get
            {
                return this._BorrowerEmail;
            }
            set
            {
                this.OnBorrowerEmailChanging(value);
                this._BorrowerEmail = value;
                this.OnBorrowerEmailChanged();
                this.OnPropertyChanged("BorrowerEmail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BorrowerEmail;
        partial void OnBorrowerEmailChanging(string value);
        partial void OnBorrowerEmailChanged();
        /// <summary>
        /// There are no comments for Property BorrowerSms in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowerSms")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BorrowerSms is required.")]
        public virtual string BorrowerSms
        {
            get
            {
                return this._BorrowerSms;
            }
            set
            {
                this.OnBorrowerSmsChanging(value);
                this._BorrowerSms = value;
                this.OnBorrowerSmsChanged();
                this.OnPropertyChanged("BorrowerSms");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BorrowerSms;
        partial void OnBorrowerSmsChanging(string value);
        partial void OnBorrowerSmsChanged();
        /// <summary>
        /// There are no comments for Property CountryCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryCode")]
        [global::System.ComponentModel.DataAnnotations.StringLengthAttribute(5, ErrorMessage = "CountryCode cannot be longer than 5 characters.")]
        public virtual string CountryCode
        {
            get
            {
                return this._CountryCode;
            }
            set
            {
                this.OnCountryCodeChanging(value);
                this._CountryCode = value;
                this.OnCountryCodeChanged();
                this.OnPropertyChanged("CountryCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CountryCode;
        partial void OnCountryCodeChanging(string value);
        partial void OnCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Transactions")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> Transactions
        {
            get
            {
                return this._Transactions;
            }
            set
            {
                this.OnTransactionsChanging(value);
                this._Transactions = value;
                this.OnTransactionsChanged();
                this.OnPropertyChanged("Transactions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _Transactions = new global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTransactionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> value);
        partial void OnTransactionsChanged();
        /// <summary>
        /// There are no comments for Property User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "User is required.")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this.OnUserChanging(value);
                this._User = value;
                this.OnUserChanged();
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.User _User;
        partial void OnUserChanging(global::LendngView.Odata.LendingTrackerApi.Models.User value);
        partial void OnUserChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
