//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12/7/2024 1:01:31 PM
namespace LendngView.Odata.LendingTrackerApi.Models
{
    /// <summary>
    /// There are no comments for ItemSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ItemSingle")]
    public partial class ItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Item>
    {
        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ItemSingle object.
        /// </summary>
        public ItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Item> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.UserSingle Owner
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Owner == null))
                {
                    this._Owner = new global::LendngView.Odata.LendingTrackerApi.Models.UserSingle(this.Context, GetPath("Owner"));
                }
                return this._Owner;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.UserSingle _Owner;
        /// <summary>
        /// There are no comments for Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Transactions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> Transactions
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Transactions == null))
                {
                    this._Transactions = Context.CreateQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction>(GetPath("Transactions"));
                }
                return this._Transactions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _Transactions;
    }
    /// <summary>
    /// There are no comments for Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ItemId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ItemId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Item")]
    public partial class Item : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="itemName">Initial value of ItemName.</param>
        /// <param name="ownerId">Initial value of OwnerId.</param>
        /// <param name="owner">Initial value of Owner.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Item CreateItem(int itemId, string itemName, global::System.Guid ownerId, global::LendngView.Odata.LendingTrackerApi.Models.User owner)
        {
            Item item = new Item();
            item.ItemId = itemId;
            item.ItemName = itemName;
            item.OwnerId = ownerId;
            if ((owner == null))
            {
                throw new global::System.ArgumentNullException("owner");
            }
            item.Owner = owner;
            return item;
        }
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ItemId is required.")]
        public virtual int ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ItemId;
        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property ItemName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ItemName is required.")]
        public virtual string ItemName
        {
            get
            {
                return this._ItemName;
            }
            set
            {
                this.OnItemNameChanging(value);
                this._ItemName = value;
                this.OnItemNameChanged();
                this.OnPropertyChanged("ItemName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ItemName;
        partial void OnItemNameChanging(string value);
        partial void OnItemNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property OwnerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OwnerId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OwnerId is required.")]
        public virtual global::System.Guid OwnerId
        {
            get
            {
                return this._OwnerId;
            }
            set
            {
                this.OnOwnerIdChanging(value);
                this._OwnerId = value;
                this.OnOwnerIdChanged();
                this.OnPropertyChanged("OwnerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _OwnerId;
        partial void OnOwnerIdChanging(global::System.Guid value);
        partial void OnOwnerIdChanged();
        /// <summary>
        /// There are no comments for Property IsAvailable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsAvailable")]
        public virtual global::System.Nullable<bool> IsAvailable
        {
            get
            {
                return this._IsAvailable;
            }
            set
            {
                this.OnIsAvailableChanging(value);
                this._IsAvailable = value;
                this.OnIsAvailableChanged();
                this.OnPropertyChanged("IsAvailable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _IsAvailable;
        partial void OnIsAvailableChanging(global::System.Nullable<bool> value);
        partial void OnIsAvailableChanged();
        /// <summary>
        /// There are no comments for Property CreatedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedAt")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                this.OnCreatedAtChanging(value);
                this._CreatedAt = value;
                this.OnCreatedAtChanged();
                this.OnPropertyChanged("CreatedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedAt;
        partial void OnCreatedAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedAtChanged();
        /// <summary>
        /// There are no comments for Property Owner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Owner")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Owner is required.")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.User Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this.OnOwnerChanging(value);
                this._Owner = value;
                this.OnOwnerChanged();
                this.OnPropertyChanged("Owner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.User _Owner;
        partial void OnOwnerChanging(global::LendngView.Odata.LendingTrackerApi.Models.User value);
        partial void OnOwnerChanged();
        /// <summary>
        /// There are no comments for Property Transactions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Transactions")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> Transactions
        {
            get
            {
                return this._Transactions;
            }
            set
            {
                this.OnTransactionsChanging(value);
                this._Transactions = value;
                this.OnTransactionsChanged();
                this.OnPropertyChanged("Transactions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _Transactions = new global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTransactionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> value);
        partial void OnTransactionsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
