//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12/7/2024 1:01:31 PM
namespace LendngView.Odata.LendingTrackerApi.Models
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.User as global::LendngView.Odata.LendingTrackerApi.Models.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.User> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::LendngView.Odata.LendingTrackerApi.Models.UserSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.User as global::LendngView.Odata.LendingTrackerApi.Models.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="userId">The value of userId</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.User> _source,
            global::System.Guid userId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserId", userId }
            };
            return new global::LendngView.Odata.LendingTrackerApi.Models.UserSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Borrower as global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Borrower> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Borrower as global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="borrowerId">The value of borrowerId</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Borrower> _source,
            global::System.Guid borrowerId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "BorrowerId", borrowerId }
            };
            return new global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Item as global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Item> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Item as global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="itemId">The value of itemId</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Item> _source,
            int itemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ItemId", itemId }
            };
            return new global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Transaction as global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::LendngView.Odata.LendingTrackerApi.Models.Transaction as global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="transactionId">The value of transactionId</param>
        public static global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::LendngView.Odata.LendingTrackerApi.Models.Transaction> _source,
            int transactionId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "TransactionId", transactionId }
            };
            return new global::LendngView.Odata.LendingTrackerApi.Models.TransactionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
