//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 12/7/2024 1:01:31 PM
namespace LendngView.Odata.LendingTrackerApi.Models
{
    /// <summary>
    /// There are no comments for TransactionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TransactionSingle")]
    public partial class TransactionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Transaction>
    {
        /// <summary>
        /// Initialize a new TransactionSingle object.
        /// </summary>
        public TransactionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TransactionSingle object.
        /// </summary>
        public TransactionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TransactionSingle object.
        /// </summary>
        public TransactionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Transaction> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Borrower in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Borrower")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle Borrower
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Borrower == null))
                {
                    this._Borrower = new global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle(this.Context, GetPath("Borrower"));
                }
                return this._Borrower;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.BorrowerSingle _Borrower;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Item")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle Item
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Item == null))
                {
                    this._Item = new global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle(this.Context, GetPath("Item"));
                }
                return this._Item;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.ItemSingle _Item;
        /// <summary>
        /// There are no comments for Lender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Lender")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.UserSingle Lender
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Lender == null))
                {
                    this._Lender = new global::LendngView.Odata.LendingTrackerApi.Models.UserSingle(this.Context, GetPath("Lender"));
                }
                return this._Lender;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.UserSingle _Lender;
    }
    /// <summary>
    /// There are no comments for Transaction in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TransactionId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("TransactionId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Transaction")]
    public partial class Transaction : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="transactionId">Initial value of TransactionId.</param>
        /// <param name="lenderId">Initial value of LenderId.</param>
        /// <param name="borrowerId">Initial value of BorrowerId.</param>
        /// <param name="itemId">Initial value of ItemId.</param>
        /// <param name="borrowedAt">Initial value of BorrowedAt.</param>
        /// <param name="dueDate">Initial value of DueDate.</param>
        /// <param name="borrower">Initial value of Borrower.</param>
        /// <param name="item">Initial value of Item.</param>
        /// <param name="lender">Initial value of Lender.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Transaction CreateTransaction(int transactionId, 
                    global::System.Guid lenderId, 
                    global::System.Guid borrowerId, 
                    int itemId, 
                    global::System.DateTimeOffset borrowedAt, 
                    global::System.DateTimeOffset dueDate, 
                    global::LendngView.Odata.LendingTrackerApi.Models.Borrower borrower, 
                    global::LendngView.Odata.LendingTrackerApi.Models.Item item, 
                    global::LendngView.Odata.LendingTrackerApi.Models.User lender)
        {
            Transaction transaction = new Transaction();
            transaction.TransactionId = transactionId;
            transaction.LenderId = lenderId;
            transaction.BorrowerId = borrowerId;
            transaction.ItemId = itemId;
            transaction.BorrowedAt = borrowedAt;
            transaction.DueDate = dueDate;
            if ((borrower == null))
            {
                throw new global::System.ArgumentNullException("borrower");
            }
            transaction.Borrower = borrower;
            if ((item == null))
            {
                throw new global::System.ArgumentNullException("item");
            }
            transaction.Item = item;
            if ((lender == null))
            {
                throw new global::System.ArgumentNullException("lender");
            }
            transaction.Lender = lender;
            return transaction;
        }
        /// <summary>
        /// There are no comments for Property TransactionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TransactionId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TransactionId is required.")]
        public virtual int TransactionId
        {
            get
            {
                return this._TransactionId;
            }
            set
            {
                this.OnTransactionIdChanging(value);
                this._TransactionId = value;
                this.OnTransactionIdChanged();
                this.OnPropertyChanged("TransactionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _TransactionId;
        partial void OnTransactionIdChanging(int value);
        partial void OnTransactionIdChanged();
        /// <summary>
        /// There are no comments for Property LenderId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LenderId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LenderId is required.")]
        public virtual global::System.Guid LenderId
        {
            get
            {
                return this._LenderId;
            }
            set
            {
                this.OnLenderIdChanging(value);
                this._LenderId = value;
                this.OnLenderIdChanged();
                this.OnPropertyChanged("LenderId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _LenderId;
        partial void OnLenderIdChanging(global::System.Guid value);
        partial void OnLenderIdChanged();
        /// <summary>
        /// There are no comments for Property BorrowerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowerId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BorrowerId is required.")]
        public virtual global::System.Guid BorrowerId
        {
            get
            {
                return this._BorrowerId;
            }
            set
            {
                this.OnBorrowerIdChanging(value);
                this._BorrowerId = value;
                this.OnBorrowerIdChanged();
                this.OnPropertyChanged("BorrowerId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _BorrowerId;
        partial void OnBorrowerIdChanging(global::System.Guid value);
        partial void OnBorrowerIdChanged();
        /// <summary>
        /// There are no comments for Property ItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ItemId is required.")]
        public virtual int ItemId
        {
            get
            {
                return this._ItemId;
            }
            set
            {
                this.OnItemIdChanging(value);
                this._ItemId = value;
                this.OnItemIdChanged();
                this.OnPropertyChanged("ItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ItemId;
        partial void OnItemIdChanging(int value);
        partial void OnItemIdChanged();
        /// <summary>
        /// There are no comments for Property BorrowedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BorrowedAt")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BorrowedAt is required.")]
        public virtual global::System.DateTimeOffset BorrowedAt
        {
            get
            {
                return this._BorrowedAt;
            }
            set
            {
                this.OnBorrowedAtChanging(value);
                this._BorrowedAt = value;
                this.OnBorrowedAtChanged();
                this.OnPropertyChanged("BorrowedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _BorrowedAt;
        partial void OnBorrowedAtChanging(global::System.DateTimeOffset value);
        partial void OnBorrowedAtChanged();
        /// <summary>
        /// There are no comments for Property ReturnedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ReturnedAt")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ReturnedAt
        {
            get
            {
                return this._ReturnedAt;
            }
            set
            {
                this.OnReturnedAtChanging(value);
                this._ReturnedAt = value;
                this.OnReturnedAtChanged();
                this.OnPropertyChanged("ReturnedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ReturnedAt;
        partial void OnReturnedAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnReturnedAtChanged();
        /// <summary>
        /// There are no comments for Property DueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DueDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DueDate is required.")]
        public virtual global::System.DateTimeOffset DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this.OnDueDateChanging(value);
                this._DueDate = value;
                this.OnDueDateChanged();
                this.OnPropertyChanged("DueDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _DueDate;
        partial void OnDueDateChanging(global::System.DateTimeOffset value);
        partial void OnDueDateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Borrower in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Borrower")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Borrower is required.")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.Borrower Borrower
        {
            get
            {
                return this._Borrower;
            }
            set
            {
                this.OnBorrowerChanging(value);
                this._Borrower = value;
                this.OnBorrowerChanged();
                this.OnPropertyChanged("Borrower");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.Borrower _Borrower;
        partial void OnBorrowerChanging(global::LendngView.Odata.LendingTrackerApi.Models.Borrower value);
        partial void OnBorrowerChanged();
        /// <summary>
        /// There are no comments for Property Item in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Item")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Item is required.")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.Item Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this.OnItemChanging(value);
                this._Item = value;
                this.OnItemChanged();
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.Item _Item;
        partial void OnItemChanging(global::LendngView.Odata.LendingTrackerApi.Models.Item value);
        partial void OnItemChanged();
        /// <summary>
        /// There are no comments for Property Lender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Lender")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Lender is required.")]
        public virtual global::LendngView.Odata.LendingTrackerApi.Models.User Lender
        {
            get
            {
                return this._Lender;
            }
            set
            {
                this.OnLenderChanging(value);
                this._Lender = value;
                this.OnLenderChanged();
                this.OnPropertyChanged("Lender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::LendngView.Odata.LendingTrackerApi.Models.User _Lender;
        partial void OnLenderChanging(global::LendngView.Odata.LendingTrackerApi.Models.User value);
        partial void OnLenderChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
