name: Manual Work Flow For Development

env:
    APP_LOCATION: "/src/view/blazor"

on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Nme'
                type: 'string'
                default: 'test'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "We actually did something"
      - run: echo "${{inputs.name}}"
      - run: echo "${{ secrets.GITHUB_TOKEN}}"
      - run: echo "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}"
      - run: echo "${{ env.APP_LOCATION}}"

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #     with:
    #       repository: Lendingtracker
    #       ref: main

    #   - name: Setup .Net
    #     uses: actions/setup-dotnet@v4.1.0
    #     with:
    #       dotnet-version: '9.0'

    #   - name: Restore dependencies
    #     run: dotnet restore

    #   - name: Build DotNet
    #     uses: Elskom/build-dotnet@main
    #     with:
    #       SOLUTION_FILE_PATH: /src/view/blazor/LendingView.sln
